### ISSUE TITLE
No way to differentiate code items and code links

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/sphinx_3dr_theme#13]
Inline code items (marked up with double backticks) and code references (links, marked up with :py:class:`whatever`) appear the same. A working link code link should be highlighted differently.

**Comment by kaitlynhova** [comment]
I added a hover state for the links in the navigation_fixes branch that was just pushed to production

**Comment by hamishwillee** [comment]
Reopening. I think this looks cool, but it doesn't work on mobile where you have no ability to hover. Usually I would also prefer to know that a link is a link without having to perform any specific user interaction.

No need to remove what it does now, but perhaps make the linked code items "link text" colour (blue?). If that doesn't work for you, some other visual difference that doesn't require an action to check.

**Comment by kaitlynhova** [comment]
Hey! Does this work? I made any code that was a link the standard link blue color: 

![screen shot 2015-06-15 at 2 27 04 pm](https://cloud.githubusercontent.com/assets/5474124/8171160/b56f2e8e-136a-11e5-9e8d-dbaba37e5a20.png)

**Comment by hamishwillee** [comment]
@kaitlynhova Looks great to me.

**Comment by kaitlynhova** [comment]
Cool -- all of the changes live on here : https://github.com/3drobotics/sphinx_3dr_theme/pull/28 .
Once it's merged into master all will be well~

**Comment by kaitlynhova** [comment]
@hamishwillee it's up on production, now.

**Comment by hamishwillee** [comment]
Awesome. I'm happy with this. Closed.
