### ISSUE TITLE
Sidebar should open with "page TOC" for current document

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/sphinx_3dr_theme#18]
Currently the sidebar TOC shows displays page titles only. When a page is opened, the toc should expand at that point to include the contents for the page itself.

This is next step from #17.

**Comment by mrpollo** [comment]
I think there needs to be some research as to how to do this, right now that TOC is not being rendered on the sidebar by the sphinx helpers, does this make sense?

**Comment by hamishwillee** [comment]
Yes it makes sense. I don't know how it should be done, I just know that I want it done :-) 

An example to try to understand how this might be implemented is [here](http://kripken.github.io/emscripten-site/docs/site/about.html#building-the-site)

**Comment by hamishwillee** [comment]
@kaitlynhova @mrpollo Can we get this done please - it is killing the usability of some of the docs.

**Comment by mrpollo** [comment]
@kaitlynhova do you have everything you need to get this done?

**Comment by hamishwillee** [comment]
@kaitlynhova Thanks very much for recent update #32. This is ALMOST what I want. At the moment it is opening every page-TOC below the current level. What I would like is that it just have the open page toc for the current page. So for the getting started page it would look like this:

![image](https://cloud.githubusercontent.com/assets/5368500/8343172/ecbe6118-1b15-11e5-8581-8c016bf2af7c.png)

The [Guide](http://python.dronekit.io/guide/index.html) top level the page has no inner headings, so it wouldn't show a page TOC at all - this would look just like it did before.

The exact behaviour required can be seen on this site: http://kripken.github.io/emscripten-site/docs/porting/guidelines/portability_guidelines.html

**Comment by kaitlynhova** [comment]
Gotcha, @hamishwillee --- I just pushed this up:
https://github.com/3drobotics/sphinx_3dr_theme/pull/33

When @mrpollo has time to merge it and push to production you can take a look : )

**Comment by hamishwillee** [comment]
@kaitlynhova It is a thing of beauty. Closing this issue now.
