### ISSUE TITLE
How is this used in a Sphinx project?

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/sphinx_3dr_theme#2]
I expected to be able to use this in the normal way:
1. Get the theme
   sudo pip install sphinx_3dr_theme
2. In the conf.py
   import sphinx_3dr_theme
   html_theme = 'sphinx_3dr_theme'
   html_theme_path = [sphinx_3dr_theme.get_html_theme_path()]

However running the drone-kit python docs (e.g. this conf.py) it fails due to missing [conf.py](https://github.com/diydrones/dronekit-python/blob/master/docs/conf.py) in your theme (and yes, this does appear to be missing from the pip installation.

What is the correct way to use this with https://github.com/diydrones/dronekit-python ?

**Comment by mrpollo** [comment]
We need to fix the pip package `setup.py`` to include more of the sphinx files from the source before it can be used as a standalone package, right now we included the repository on our PYTHONPATH on our build server to be able to get the doc theme you see here http://python.dronekit.io/ fix to come

**Comment by hamishwillee** [comment]
Thanks. Just what we need - it is much easier to sanity check both the theme and content changes when we can see them together. I'll wait on this fix rather than updating my PYTHONPATH.

**Comment by mrpollo** [comment]
@hamishwillee i believe you can now use this package via pip install :)

closed by 11f8e3a4e8297c128c4a89ef1c04fa87c91eacd4

**Comment by hamishwillee** [comment]
Lovely. Note that the version number wasn't updated, but since I'm probably the only one who has tried this that shouldn't affect anyone else. Thank you. I'll add a note on the android/python docs.

**Comment by mrpollo** [comment]
I updated the pip package version to 0.0.6 here https://github.com/3drobotics/sphinx_3dr_theme/blob/master/sphinx_3dr_theme/__init__.py#L3 what version is the one you see?

**Comment by hamishwillee** [comment]
I based my comment on the fact that when I first did "pip install sphinx_3dr_theme" the system told me that I already had the head revision. In order to get this to install I first had to uninstall the old version. I assumed this was likely due to incorrect stored revision information.

So, looks like you did the right thing - please ignore me!
