### ISSUE TITLE
Bullets have some issues

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/sphinx_3dr_theme#20]
This still has some issues following #5 being closed.
1. Odd misalignment - more visible magnified 

![image](https://cloud.githubusercontent.com/assets/5368500/7763097/46757752-007f-11e5-8242-9a90c366fc69.png)

![image](https://cloud.githubusercontent.com/assets/5368500/7763106/89a5b4b0-007f-11e5-9db3-183ca8c0dbcf.png)
1. The next lines are indented back which to my mind looks really odd. Shouldn't subsequent lines align with the first line? 

![image](https://cloud.githubusercontent.com/assets/5368500/7763134/cb465e56-007f-11e5-983a-e4b837e3c214.png)

**Comment by hamishwillee** [comment]
The size of the bullet also looks a little big to me, compared to the text size.

**Comment by kaitlynhova** [comment]
Hey @hamishwillee good eye! I fixed it in this branch: https://github.com/3drobotics/sphinx_3dr_theme/tree/scroll-to-fixes

Does that work for you? I like the bullets being super large for legibility and design eye reasons. @mrpollo , do you want them to be smaller?

**Comment by hamishwillee** [comment]
Hi @kaitlynhova 

I can't view or build this yet, because I haven't got that working (@mrpollo plans to do a vagrant to simplify this). Can you cut-paste an example here for me. 

I do agree re bullets being big. Perhaps the font for the text is just a little small relatively though.

Cheers
H

**Comment by kaitlynhova** [comment]
Hey! Sorry for the delay, I didn't realize you couldn't view the changes. Here is a screenshot of the new bullets: 

![screen shot 2015-06-15 at 2 10 36 pm](https://cloud.githubusercontent.com/assets/5474124/8170847/67369d94-1368-11e5-8c4a-a11547df875e.png)

Does that work for you? I also made them smaller ~

**Comment by hamishwillee** [comment]
@kaitlynhova Looks good to me! Thank you.

**Comment by kaitlynhova** [comment]
@hamishwillee check it out on production, now.

**Comment by hamishwillee** [comment]
@kaitlynhova I am VERY happy with the ordered and un-ordered list appearance now. Just the right amount of space. Tested on chrome only.
