### ISSUE TITLE
Links take you below the target mk2

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/sphinx_3dr_theme#21]
I use explicit references to link to documents. This allows me to link to headings, and to documents, even if the documents move around.

The links are taking me below the target. For example, there is an anchor at the top of the page: http://python.dronekit.io/quick_start.html#quick-start

I get this:
![image](https://cloud.githubusercontent.com/assets/5368500/7763238/6bf9631a-0081-11e5-9913-285b48d89e7c.png)
I want this:
![image](https://cloud.githubusercontent.com/assets/5368500/7763260/92b2bfb0-0081-11e5-9f51-0765eb521d7b.png)

Other "top of page" example is http://python.dronekit.io/guide/getting_started.html#get-started

Here is an in-page heading link to a heading: http://python.dronekit.io/quick_start.html#vagrant-sitl-from-full-image - see the heading is off-screen:

![image](https://cloud.githubusercontent.com/assets/5368500/7763273/c220f686-0081-11e5-8fbb-0c4122094d36.png)

**Comment by kaitlynhova** [comment]
@hamishwillee  All of the links are working for me. The links for the top of the page are not using the id anchor tags, but instead are like this:

EX: Get Started:
http://python.dronekit.io/guide/getting_started.html

Where did you see a link that was "http://python.dronekit.io/guide/getting_started.html#get-started" ?

Either way, does this branch fix it for you?:
https://github.com/3drobotics/sphinx_3dr_theme/tree/scroll-to-fixes

**Comment by hamishwillee** [comment]
@kaitlynhova The _standard_ link is as you say, but I can put a heading link at the top of the page if I want - just as I can to any other heading (e.g. see http://python.dronekit.io/quick_start.html#vagrant-sitl-from-full-image)

This is declared in sphinx like this

```
.. _my-anchor:

============
Page Heading
============
```

and linked using 

```
:ref:`Anchor Text <my-anchor>`
```

The reason I often do this is that this type of reference link doesn't care where the page is. If I move the page all the links still work. Just makes things a bit easier.

**Comment by hamishwillee** [comment]
And of course, as per https://github.com/diydrones/dronekit-python/issues/162 the problem occurs for any internal link, not just the ones at the top of the page.

**Comment by mrpollo** [comment]
@kaitlynhova I think this is referring to the auto/magic/smooth scroll and the topnav having a conflict of interest, I think they need some glitter-power

**Comment by kaitlynhova** [comment]
Hey! Does this fix it for you? --> 
https://github.com/3drobotics/sphinx_3dr_theme/tree/internal-links-fix

**Comment by mrpollo** [comment]
I don't think they can test that @kaitlynhova, why not post a Screenshot?

**Comment by kaitlynhova** [comment]
Sure! Here is what all of the header links will look like now (EX: /quick_start.html#vagrant-sitl-from-full-image) -->
![screen shot 2015-06-15 at 1 48 50 pm](https://cloud.githubusercontent.com/assets/5474124/8170461/8d312b48-1365-11e5-94db-b6ff542802d5.png)

**Comment by hamishwillee** [comment]
Looks nice, but again, not quite a "test". @mrpollo would be great if that vagrant build of the theme were forthcoming. @kaitlynhova - what I do to share is dump the built content on dropbox and share the public link - this is testable. Just an idea!

**Comment by kaitlynhova** [comment]
@hamishwillee check it out on production, now

**Comment by hamishwillee** [comment]
@kaitlynhova Direct links to link at top of page work!. 

Link to internal heading works well enough (basically they work perfectly if you click the link into another page: e.g. http://python.dronekit.io/guide/vehicle_state_and_parameters.html#vehicle-state-disrecommended) but if you click on the link within the page (as shown) the scrolling doesn't quite get to the right heading). As I said, good enough! Thank you. Closed

![image](https://cloud.githubusercontent.com/assets/5368500/8223970/9f5d7d76-15c2-11e5-857d-cead0b5316a1.png)
