### ISSUE TITLE
3DR Logo missing from navbar on IE/Firefox #39

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/sphinx_3dr_theme#23]
The "3DR" logo is displayed on top left of navbar on Chrome, but not Firefox or IE (for chrome I tried on a fresh browser, so I think it is not a caching issue).

See https://github.com/diydrones/dronekit-python/issues/39 (closed, because I am opening here) for diagrams

**Comment by kaitlynhova** [comment]
Hey! Can you check now? 

http://python.dronekit.io/

**Comment by hamishwillee** [comment]
Perfect, thank you.
