### ISSUE TITLE
No obvious link in Python docs back to the Python home page

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/sphinx_3dr_theme#3]
If you navigate to any sidebar link, then there is no obvious UI option to go back to the home page/table of contents. 

There is actually an option - clicking the top header bar option for Android/Python - but this doesn't feel like obvious navigation to me. Adding a "Table of Contents" link at the bottom of the glossary or a "Home" at the top might help.

**Comment by mrpollo** [comment]
@kaitlynhova do you think you can add this?, does this make sense?

**Comment by kaitlynhova** [comment]
I think the logo in the top left nav is pretty standard to go back to "home" (http://dronekit.io/)-- but what if we got rid of all of the 3DR links in the footer and just had : 

![screen shot 2015-03-31 at 4 18 53 pm](https://cloud.githubusercontent.com/assets/5474124/6931421/abfc154a-d7c1-11e4-8192-0d8a28c70853.png)

What do you think?

**Comment by hamishwillee** [comment]
I have confused you by using poor terminology. What I mean by home link for this issue is http://python.dronekit.io/ - the Documentation Home link . I have renamed this issue appropriately.

So go to that page, and then go to a sidebar option, there is no way to get back to http://python.dronekit.io/ except via the navbar Python link. Now you could argue that the navbar link is sufficient. I am not so sure.

W.r.t. your comment above that would be a different/separate issue. I wouldn't change it as you have suggested, though I might change "Backed By" to something else ("Supported by, Created by")? Depends on what Backed By is supposed to imply. The links are fine as long as it is clear that they belong to 3DRobotics.

**Comment by hamishwillee** [comment]
Looks good.
