### ISSUE TITLE
CSS does not provide CSS to support restructuredtext notes, tips, warnings, hints

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/sphinx_3dr_theme#4]
The ability to add notes, hints, tips, warnings is very useful. Most themes support this CSS. Can we get it added please. See http://udig.refractions.net/files/docs/latest/user/docguide/sphinxSyntax.html#notes-and-warnings

**Comment by mrpollo** [comment]
can you provide us with links to where this are being used in our docs right now please, I want to get this fixed.

**Comment by kaitlynhova** [comment]
I can grab the css for these IDs no prob, but do we currently have any notes/warnings on the current site?

**Comment by mrpollo** [comment]
hold on adding new css/ids, we need to identify what we need to do first

**Comment by hamishwillee** [comment]
This is not used on the site yet - but it will be as soon as this pull request goes in https://github.com/diydrones/dronekit-python/pull/55

In the meantime, you can see how it renders in https://dl.dropboxusercontent.com/u/3067678/share2/dronekit-python/html/contributing.html . Images below show a tip and a note without styling from this link.

![image](https://cloud.githubusercontent.com/assets/5368500/7058360/f5437d86-dea3-11e4-8555-117814b397dc.png)

![image](https://cloud.githubusercontent.com/assets/5368500/7058365/17eb41e8-dea4-11e4-8256-017b2e31eb33.png)

**Comment by mrpollo** [comment]
Cool, I'll take care of this, thanks @hamishwillee

**Comment by hamishwillee** [comment]
@mrpollo - a few more for you that are "related"
1. todo directive - creates a class item admonition-todo . YOu can see this in [my dropbox link](https://dl.dropboxusercontent.com/u/3067678/share2/dronekit-python/html/automodule.html) and will appear in docs when https://github.com/diydrones/dronekit-python/pull/58https://github.com/diydrones/dronekit-python/pull/58 is merged: 

![image](https://cloud.githubusercontent.com/assets/5368500/7061368/5e30519a-ded4-11e4-90c2-4097340b1a24.png)
1. Versionchanged - in same docs as above. This marked up as div with class "versionchanged". The image below shows the rendering "Changed in version ...":

![image](https://cloud.githubusercontent.com/assets/5368500/7061376/8b291664-ded4-11e4-8268-cb1f5b888652.png)
1. There is also a warning added here, in get_mission. See rendering below

![image](https://cloud.githubusercontent.com/assets/5368500/7061421/fcdbbdf2-ded4-11e4-8111-1c41e935b8bf.png)

**Comment by hamishwillee** [comment]
@kaitlynhova - I think the tips, notes, warning part of this is quite high priority. I'd add them myself but am waiting on #15. In any case, I'm sure your look and feel would be better!

**Comment by hamishwillee** [comment]
I have reopened this. There may be CSS, but it is not fit for purpose.

The warnings, notes, tips etc are not visually differentiated. See the two examples below - for neither the Note or the Warning would I feel "warned" or that I needed to take note of something.

![image](https://cloud.githubusercontent.com/assets/5368500/7763034/51124240-007e-11e5-918f-5cbe5cd003b5.png)

![image](https://cloud.githubusercontent.com/assets/5368500/7763042/6a09b18e-007e-11e5-8e15-52ac6e44356c.png)

Ideally these should be coloured box outs of some kind. They could all share the same colour if the text describing the type of note is sufficiently emphasized. Often different colours are used for different boxes.

**Comment by kaitlynhova** [comment]
Got it! Here is the branch for Ramon : https://github.com/3drobotics/sphinx_3dr_theme/pull/28

This is what they all look like, now (tips are the same as hints in style): 
![screen shot 2015-06-15 at 3 40 42 pm](https://cloud.githubusercontent.com/assets/5474124/8172400/1494d4c2-1375-11e5-999c-72e11c34035b.png)
![screen shot 2015-06-15 at 3 40 46 pm](https://cloud.githubusercontent.com/assets/5474124/8172401/149e1c80-1375-11e5-89f4-b4b47536eadc.png)
![screen shot 2015-06-15 at 3 40 51 pm](https://cloud.githubusercontent.com/assets/5474124/8172402/14a09140-1375-11e5-9a68-443e1cefbe83.png)

Do those work? ^

**Comment by hamishwillee** [comment]
@kaitlynhova I like this, but could we have the text "tip" "warning, etc in bold?

**Comment by hamishwillee** [comment]
@kaitlynhova I also haven't checked todo boxes or  [seealso](http://udig.refractions.net/files/docs/latest/user/docguide/sphinxSyntax.html#notes-and-warnings). If there is a generic "base class" might be worth just having a default box in grey or similar so that at least if we don't have specific colouring the text is highlighted.

**Comment by kaitlynhova** [comment]
Sure! I just updated it. Does this look alright? They will all have this font hierarchy --->

![screen shot 2015-06-15 at 3 52 05 pm](https://cloud.githubusercontent.com/assets/5474124/8172543/9ba09b4e-1376-11e5-91de-36e58d42944c.png)

**Comment by kaitlynhova** [comment]
@hamishwillee where in the docs do we have a see also? Is it just "seealso" class? 
- I just added styles so that would make seealso class look like this: 
  ![screen shot 2015-06-15 at 3 56 45 pm](https://cloud.githubusercontent.com/assets/5474124/8172597/27856cf2-1377-11e5-979f-a99c4d4df2cb.png)

**Comment by hamishwillee** [comment]
@kaitlynhova We don't have it - but we could :-) There is another list of the paragraph markup we might [choose to use here](http://sphinx-doc.org/markup/para.html) from which you can get the classes for seealso, versionadded etc..

**Comment by mrpollo** [comment]
@kaitlynhova what happened with the border radius, it looked good IMO

**Comment by mrpollo** [comment]
@hamishwillee can you guide Kaitlyn on how to add one?, she needs to see the actual HTML output so she can add styles specific to the class that sphinx is rendering

**Comment by kaitlynhova** [comment]
@mrpollo I don't think I took out the border radius today, but I think my taking the border away made it less rounded looking. Right now it should be a border radius of 4px -- how high do you want to go?

**Comment by hamishwillee** [comment]
@mrpollo @kaitlynhova That link above shows exactly how to add all the different markup - http://sphinx-doc.org/markup/para.html

**Comment by kaitlynhova** [comment]
@hamishwillee everything is up on production, now.

**Comment by hamishwillee** [comment]
@kaitlynhova Lovely. Thank you. Closed.
