### ISSUE TITLE
Links to references take you below the target

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/sphinx_3dr_theme#7]
Consider [this link to the Vehicle.flush](https://dl.dropboxusercontent.com/u/3067678/share2/dronekit-python/html/automodule.html#droneapi.lib.Vehicle.flush) method (on my dropbox).

It takes you here (just below the heading): 
![image](https://cloud.githubusercontent.com/assets/5368500/7079034/d616366e-df62-11e4-8ec7-fbbf2f429663.png)

When it should take you here (just above the heading):
![image](https://cloud.githubusercontent.com/assets/5368500/7079048/f0461176-df62-11e4-9dde-6442a501cc61.png)

A version of the autodocs with these links (for manual testing) will be available when this changelist is merged.
https://github.com/diydrones/dronekit-python/pull/58

In the meantime you can easily test just by selecting links from the [genindex](http://python.dronekit.io/genindex.html) on the live site.

**Comment by kaitlynhova** [comment]
The links are now going to the correct place as of today's merge of the "navigation_fixes" into production.

**Comment by hamishwillee** [comment]
Fixes code links (thanks!). Still a problem for other types of links. I'll create a new issue.
